import type { SkillIcon } from '@/lib/iconTypes';
import { CursorIcon } from '@/components/icons/CursorIcon';
import { GrokIcon } from '@/components/icons/GrokIcon';
import { DiAws, DiJava } from 'react-icons/di';
import {
  SiClaude,
  SiSharp,
  SiDocker,
  SiExpress,
  SiFastapi,
  SiFirebase,
  SiFlask,
  SiGithubcopilot,
  SiGit,
  SiGooglegemini,
  SiGraphql,
  SiGulp,
  SiJavascript,
  SiJest,
  SiJenkins,
  SiMongodb,
  SiMysql,
  SiNextdotjs,
  SiNodedotjs,
  SiOllama,
  SiOpenai,
  SiPhp,
  SiPostgresql,
  SiPython,
  SiReact,
  SiReacthookform,
  SiReactquery,
  SiSpringboot,
  SiSupabase,
  SiTypescript,
  SiVite,
  SiWebpack,
} from 'react-icons/si';

export const SKILL_ICONS: Record<string, SkillIcon> = {
  JavaScript: SiJavascript,
  TypeScript: SiTypescript,
  Java: DiJava,
  Python: SiPython,
  PHP: SiPhp,
  'C#': SiSharp,
  React: SiReact,
  'Node.js': SiNodedotjs,
  Webpack: SiWebpack,
  'Next.js': SiNextdotjs,
  Express: SiExpress,
  GraphQL: SiGraphql,
  Gulp: SiGulp,
  Jest: SiJest,
  'Spring Boot': SiSpringboot,
  Flask: SiFlask,
  FastAPI: SiFastapi,
  Vite: SiVite,
  MySQL: SiMysql,
  PostgreSQL: SiPostgresql,
  MongoDB: SiMongodb,
  Supabase: SiSupabase,
  Git: SiGit,
  Docker: SiDocker,
  AWS: DiAws,
  Jenkins: SiJenkins,
  Firebase: SiFirebase,
  'TanStack Query': SiReactquery,
  'React Hook Form': SiReacthookform,
  Claude: SiClaude,
  Gemini: SiGooglegemini,
  OpenAI: SiOpenai,
  Ollama: SiOllama,
  Grok: GrokIcon,
  'GitHub Copilot': SiGithubcopilot,
  Cursor: CursorIcon,
  'Claude Code': SiClaude,
};

export const SKILL_ICON_COLORS: Partial<Record<string, string>> = {
  JavaScript: '#F7DF1E',
  TypeScript: '#3178C6',
  Java: '#E76F00',
  Python: '#3776AB',
  PHP: '#777BB4',
  'C#': '#512BD4',
  React: '#61DAFB',
  'Node.js': '#68A063',
  Webpack: '#8DD6F9',
  'Next.js': '#ffffff',
  Express: '#CBD5E1',
  GraphQL: '#E10098',
  Jest: '#C21325',
  'Spring Boot': '#6DB33F',
  Flask: '#ffffff',
  FastAPI: '#009688',
  Vite: '#646CFF',
  MySQL: '#4479A1',
  PostgreSQL: '#336791',
  MongoDB: '#47A248',
  Supabase: '#3FCF8E',
  Git: '#F05032',
  Docker: '#2496ED',
  AWS: '#FF9900',
  Jenkins: '#D24939',
  Firebase: '#FFCA28',
  'TanStack Query': '#FF4154',
  'React Hook Form': '#EC5990',
  Claude: '#D97757',
  Gemini: '#8E75B2',
  OpenAI: '#10A37F',
  Ollama: '#ffffff',
  Grok: '#F1F5F9',
  'GitHub Copilot': '#ffffff',
  Cursor: '#F1F5F9',
  'Claude Code': '#D97757',
};

const DEFAULT_ICON_COLOR = '#F1F5F9';

export function getSkillIcon(name: string): SkillIcon | undefined {
  return SKILL_ICONS[name];
}

export function getSkillColor(name: string): string {
  return SKILL_ICON_COLORS[name] ?? DEFAULT_ICON_COLOR;
}
