import type { SkillIcon } from '@/lib/iconTypes';
import { CursorIcon } from '@/components/icons/CursorIcon';
import { GrokIcon } from '@/components/icons/GrokIcon';
import { DiAws, DiJava } from 'react-icons/di';
import {
  SiClaude,
  SiSharp,
  SiDocker,
  SiExpress,
  SiFastapi,
  SiFirebase,
  SiFlask,
  SiGithubcopilot,
  SiGit,
  SiGooglegemini,
  SiGraphql,
  SiGulp,
  SiHtml5,
  SiCss,
  SiJavascript,
  SiJest,
  SiHelm,
  SiJenkins,
  SiMongodb,
  SiMysql,
  SiNextdotjs,
  SiNodedotjs,
  SiOllama,
  SiOpenai,
  SiPhp,
  SiPostgresql,
  SiPython,
  SiReact,
  SiReactquery,
  SiSass,
  SiSpringboot,
  SiSpinnaker,
  SiSupabase,
  SiTailwindcss,
  SiTypescript,
  SiVite,
  SiWebpack,
} from 'react-icons/si';

const DEVICON =
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons';

function devicon(folder: string, file = `${folder}-original`): string {
  return `${DEVICON}/${folder}/${file}.svg`;
}

/** Full-color transparent SVG URLs (Devicon + SVGL). */
export const SKILL_ICON_URLS: Record<string, string> = {
  JavaScript: devicon('javascript'),
  TypeScript: devicon('typescript'),
  Java: devicon('java'),
  Python: devicon('python'),
  PHP: devicon('php'),
  'C#': devicon('csharp'),
  React: devicon('react'),
  'Node.js': devicon('nodejs'),
  Webpack: devicon('webpack'),
  'Next.js': devicon('nextjs'),
  Express: 'https://skillicons.dev/icons?i=express&theme=dark',
  GraphQL: `${DEVICON}/graphql/graphql-plain.svg`,
  Gulp: `${DEVICON}/gulp/gulp-plain.svg`,
  Jest: `${DEVICON}/jest/jest-plain.svg`,
  'Spring Boot': devicon('spring'),
  Flask: 'https://skillicons.dev/icons?i=flask&theme=dark',
  FastAPI: devicon('fastapi'),
  Vite: devicon('vite'),
  MySQL: devicon('mysql'),
  PostgreSQL: devicon('postgresql'),
  MongoDB: devicon('mongodb'),
  NoSQL: devicon('mongodb'),
  Supabase: devicon('supabase'),
  Git: devicon('git'),
  Docker: devicon('docker'),
  AWS: 'https://skillicons.dev/icons?i=aws&theme=dark',
  Jenkins: devicon('jenkins'),
  'MFE / Module Federation': devicon('webpack'),
  Harness: devicon('helm'),
  Spinnaker: 'https://svgl.app/library/spinnaker.svg',
  Firebase: devicon('firebase'),
  TanStack: 'https://svgl.app/library/tanstack.svg',
  HTML: devicon('html5'),
  CSS: devicon('css3'),
  Tailwind: devicon('tailwindcss'),
  Sass: devicon('sass'),
  Claude: 'https://svgl.app/library/claude-ai-icon.svg',
  Gemini: 'https://svgl.app/library/gemini.svg',
  OpenAI: 'https://svgl.app/library/openai_dark.svg',
  Ollama: 'https://svgl.app/library/ollama_dark.svg',
  Grok: 'https://svgl.app/library/grok-dark.svg',
  'GitHub Copilot': 'https://svgl.app/library/copilot_dark.svg',
  Cursor: 'https://svgl.app/library/cursor_dark.svg',
  'Claude Code': 'https://svgl.app/library/claude-ai-icon.svg',
};

/** Fallback monochrome icons when CDN URL is unavailable. */
export const SKILL_ICONS: Record<string, SkillIcon> = {
  JavaScript: SiJavascript,
  TypeScript: SiTypescript,
  Java: DiJava,
  Python: SiPython,
  PHP: SiPhp,
  'C#': SiSharp,
  React: SiReact,
  'Node.js': SiNodedotjs,
  Webpack: SiWebpack,
  'Next.js': SiNextdotjs,
  Express: SiExpress,
  GraphQL: SiGraphql,
  Gulp: SiGulp,
  Jest: SiJest,
  'Spring Boot': SiSpringboot,
  Flask: SiFlask,
  FastAPI: SiFastapi,
  Vite: SiVite,
  MySQL: SiMysql,
  PostgreSQL: SiPostgresql,
  MongoDB: SiMongodb,
  Supabase: SiSupabase,
  Git: SiGit,
  Docker: SiDocker,
  AWS: DiAws,
  Jenkins: SiJenkins,
  'MFE / Module Federation': SiWebpack,
  Harness: SiHelm,
  Spinnaker: SiSpinnaker,
  NoSQL: SiMongodb,
  Firebase: SiFirebase,
  TanStack: SiReactquery,
  HTML: SiHtml5,
  CSS: SiCss,
  Tailwind: SiTailwindcss,
  Sass: SiSass,
  Claude: SiClaude,
  Gemini: SiGooglegemini,
  OpenAI: SiOpenai,
  Ollama: SiOllama,
  Grok: GrokIcon,
  'GitHub Copilot': SiGithubcopilot,
  Cursor: CursorIcon,
  'Claude Code': SiClaude,
};

export const SKILL_ICON_COLORS: Partial<Record<string, string>> = {
  JavaScript: '#F7DF1E',
  TypeScript: '#3178C6',
  Java: '#E76F00',
  Python: '#3776AB',
  PHP: '#777BB4',
  'C#': '#512BD4',
  React: '#61DAFB',
  'Node.js': '#68A063',
  Webpack: '#8DD6F9',
  'Next.js': '#ffffff',
  Express: '#CBD5E1',
  GraphQL: '#E10098',
  Jest: '#C21325',
  'Spring Boot': '#6DB33F',
  Flask: '#ffffff',
  FastAPI: '#009688',
  Vite: '#646CFF',
  MySQL: '#4479A1',
  PostgreSQL: '#336791',
  MongoDB: '#47A248',
  Supabase: '#3FCF8E',
  Git: '#F05032',
  Docker: '#2496ED',
  AWS: '#FF9900',
  Jenkins: '#D24939',
  'MFE / Module Federation': '#8DD6F9',
  Harness: '#00ADE4',
  Spinnaker: '#139BB4',
  NoSQL: '#47A248',
  Firebase: '#FFCA28',
  TanStack: '#FF4154',
  HTML: '#E34F26',
  CSS: '#1572B6',
  Tailwind: '#06B6D4',
  Sass: '#CC6699',
  Claude: '#D97757',
  Gemini: '#8E75B2',
  OpenAI: '#10A37F',
  Ollama: '#ffffff',
  Grok: '#F1F5F9',
  'GitHub Copilot': '#ffffff',
  Cursor: '#F1F5F9',
  'Claude Code': '#D97757',
};

const DEFAULT_ICON_COLOR = '#F1F5F9';

export function getSkillIconUrl(name: string): string | undefined {
  return Object.hasOwn(SKILL_ICON_URLS, name) ? SKILL_ICON_URLS[name] : undefined;
}

export function getSkillIcon(name: string): SkillIcon | undefined {
  return Object.hasOwn(SKILL_ICONS, name) ? SKILL_ICONS[name] : undefined;
}

export function getSkillColor(name: string): string {
  return Object.hasOwn(SKILL_ICON_COLORS, name)
    ? (SKILL_ICON_COLORS[name] ?? DEFAULT_ICON_COLOR)
    : DEFAULT_ICON_COLOR;
}
